import = [
    "C:\\Users\\baturalp\\AppData\\Roaming\\alacritty\\themes\\_active_theme.toml",
]

shell = "pwsh"

working_directory = "C:\\Users\\baturalp"

[window]
dimensions.lines = 35
dimensions.columns = 140
padding = { x = 7, y = 7 }

[font]
normal = { family = "CaskaydiaCove NFM" }

[mouse]
bindings = [
    { mouse = "Right", action = "Copy" }, # Copy on RMB click
]

[keyboard]
bindings = [
    { key = "Back", mods = "Control", chars = "\u0017" }, # Delete word with Ctrl+Backspace, identical to Ctrl+W, ref: https://github.com/alacritty/alacritty/issues/2930#issuecomment-1059833970
]
